name: CI
on:
  pull_request:
    branches:
      - 'main'
  workflow_call:

jobs:
  build:
    name: Build and Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
    steps:
      - name: Fetch sources
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.33.4

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm run lint

      - name: Build
        run: pnpm run build

      - name: Run unit tests
        run: pnpm run test:unit

      - name: Run integration tests
        run: |
          sudo apt-get install xvfb
          xvfb-run --auto-servernum pnpm run test:integration
        if: runner.os == 'Linux'
      - name: Run integration tests
        run: pnpm run test:integration
        if: runner.os != 'Linux'

